---
title: "Résumé"
---

```{r knit-resume, echo=FALSE, message=FALSE}
rmarkdown::render(
  "resume/Resume.Rmd",
  output_format = "pdf_document",
  output_file   = "Resume.pdf",
  output_dir    = "resume",
  quiet         = TRUE
)
```

You can view a PDF version of my résumé [here](resume/Resume (1).pdf).

# Professional Summary

Communicative, knowledgeable professional with five years experience using Cakewalk digital
audio workstation to create my own music. Fresh insight and experience with communicating
with clients, completing tasks, and developing new ideas.

# Technical Skills

- **Technological Skills:** R, Cakewalk, Scratch, FL Studio, etc.  
- **Web Technologies:** HTML, SCSS, Github, Quarto, CMS Platforms, Analytics Tools

# Education

| Degree                             | Year                          | College / Department                 | Institution         |
| ---------------------------------- | ----------------------------- | ------------------------------------ | ------------------- |
| Marketing                     | 2023 – 2028     | College of Business        | Cal Poly Pomona   |
| High School Completion | 2019 – 2023            | General Education        | De La Salle   |

# Work Experience

### Maintenance, The Club @ Livermore  
*May 2022 – August 2023*

- Cleaned and maintained facilities  
- Power washed tennis courts  
- Chlorinated pools  
- Prepared for events  

---

### Carryout, Alden Lane Nursey  
*May 2021 – August 2021*

- Cleaned and maintained facilities and animals  
- Loaded and unloaded inventory  
- Returned carry carts  
- Prepared for events  

---